dist: xenial
sudo: true
# PyCrypto .travis.yml file, for travis-ci.org testing.
# See https://travis-ci.org/dlitz/pycrypto for build status.

matrix:
  include:
    #- os: linux
    #  dist: trusty
    #  language: python
    #  python: 2.7

    #- os: linux
    #  dist: trusty
    #  language: python
    #  python: 3.5

    - os: linux
      dist: trusty
      language: python
      python: 3.6

    - os: linux
      dist: xenial
      language: python
      python: 3.7

before_install:
  # Install some package dependencies
  - sudo apt-get -qq update
  - sudo apt-get -qq install libgmp-dev
script:
  - python -tt -bb $python_flags setup.py -q build
  - python -tt -bb $python_flags setup.py test
