environment:

  matrix:
    #- TARGET_ARCH: x86
    #  PYTHON_VERSION: 2.7
    #  CONDA_INSTALL_LOCN: C:\\Miniconda

    #- TARGET_ARCH: x64
    #  PYTHON_VERSION: 2.7
    #  CONDA_INSTALL_LOCN: C:\\Miniconda-x64

    #- TARGET_ARCH: x86
    #  PYTHON_VERSION: 3.5
    #  CONDA_INSTALL_LOCN: C:\\Miniconda35

    #- TARGET_ARCH: x64
    #  PYTHON_VERSION: 3.5
    #  CONDA_INSTALL_LOCN: C:\\Miniconda35-x64

    #- TARGET_ARCH: x86
    #  PYTHON_VERSION: 3.6
    #  CONDA_INSTALL_LOCN: C:\\Miniconda36

    - TARGET_ARCH: x64
      PYTHON_VERSION: 3.6
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
      # preconfigure_args: "--without-gmp"

    - TARGET_ARCH: x64
      PYTHON_VERSION: 3.7
      CONDA_INSTALL_LOCN: C:\\Miniconda37-x64

platform:
    - x64

install:
    # Activate `conda`
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat

    # Configure conda
    - cmd: conda config --add channels conda-forge
    - cmd: conda config --set show_channel_urls true
    - cmd: conda config --set always_yes yes --set changeps1 no

    # Create conda environment
    - cmd: conda create -n test python=%PYTHON_VERSION% mpir mpfr mpc
    - cmd: call activate test

build: off

test_script:
    - cmd: python -tt %preconfigure_args% %python_flags% setup.py -q build -I%CONDA_PREFIX%\Library\include -L%CONDA_PREFIX%\Library\lib
    - cmd: python -tt %preconfigure_args% %python_flags% setup.py test

artifacts:
  - path: dist
    name: pycrypto
