environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
    # - PYTHON: "C:\\Python37-x64"
    #  PYTHON_VERSION: "3.7.x"
    #  PYTHON_ARCH: "64"
    #  python_flags:-Qnew
    #- PYTHON: "C:\\Python37-x64"
    #  PYTHON_VERSION: "3.7.x"
    #  PYTHON_ARCH: "64"
    #  python_flags:-OO
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      preconfigure_args:--without-gmp

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%" 

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
build:
  - "%PYTHON%\\python -tt %preconfigure_args% %python_flags% setup.py -q build"

test_script:
  - "%PYTHON%\\python -tt %preconfigure_args% %python_flags% setup.py test

after_test:
  - "%PYTHON%\\python  -tt %preconfigure_args% %python_flags% setup.py bdist_wheel"

artifacts:
  - path: dist
    name: pycrypto
